const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://kristineskitchenblog.com/wp-content/uploads/2021/04/buttermilk-pancakes-1200-square-for-recipe-card-40.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://images.squarespace-cdn.com/content/v1/515e1572e4b0ecbdd5aa8b32/1518405328070-T2J3HB58I5DQ7IVQCWA9/ChinaDiner_DoubleBay_010817_CREDITDominicLoneragan_0066.jpg?format=1000w',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQviYNIxq5be7gdIX1AowVlpmeJVxmLUmEP0A&usqp=CAU',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://entrackr-bucket.s3.ap-south-1.amazonaws.com/wp-content/uploads/2022/05/25104939/Country-delight-800x400.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://img.i-scmp.com/cdn-cgi/image/fit=contain,width=425,format=auto/sites/default/files/styles/768x768/public/2014/04/22/99fe973e5cc7e3b4e809defc9bb06990.jpg?itok=odtzk667',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://bilder.ngdata.no/id/189454/large.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://external-preview.redd.it/H5wUsbQwYSKQYxJII7ARXb6Jvk_-Xb30tyjbwf_MuZU.jpg?width=640&crop=smart&auto=webp&s=27dd2ccf6e6a691dcb41360b83d193952e9e7870',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://media.cntraveler.com/photos/586eb8449d2b725a71af8123/master/pass/hot-dogs-gene-and-judes-photo-credit-Nick-Holmes.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdjCRNLUW3qpgP7FK9cIAZyivGM_hZ6fUzAA&usqp=CAU',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;